import Navigation from '@/components/Navigation/navigation'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/Footer/footer'

export const metadata = {
  title: 'Legite',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navigation />
        
        {children}

        <Footer />
      </body>
    </html>
  )
}
